package com.example.springboot_quartz.model.dto;

import lombok.Data;

@Data
public class QrtzTriggers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.SCHED_NAME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.TRIGGER_NAME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String triggerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.TRIGGER_GROUP
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String triggerGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.JOB_NAME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.JOB_GROUP
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String jobGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.DESCRIPTION
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.NEXT_FIRE_TIME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private Long nextFireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.PREV_FIRE_TIME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private Long prevFireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.PRIORITY
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.TRIGGER_STATE
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String triggerState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.TRIGGER_TYPE
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String triggerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.START_TIME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private Long startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.END_TIME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private Long endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.CALENDAR_NAME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String calendarName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.MISFIRE_INSTR
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private Short misfireInstr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.JOB_DATA
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private byte[] jobData;
}