package com.example.springboot_quartz.model.dto;

import lombok.Data;

@Data
public class QrtzFiredTriggers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.SCHED_NAME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.ENTRY_ID
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String entryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.TRIGGER_NAME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String triggerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.TRIGGER_GROUP
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String triggerGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.INSTANCE_NAME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String instanceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.FIRED_TIME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private Long firedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.SCHED_TIME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private Long schedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.PRIORITY
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.STATE
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.JOB_NAME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.JOB_GROUP
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String jobGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.IS_NONCONCURRENT
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String isNonconcurrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.REQUESTS_RECOVERY
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String requestsRecovery;
}