package com.example.springboot_quartz.model.dto;

import lombok.Data;

@Data
public class QrtzSchedulerState {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_scheduler_state.SCHED_NAME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_scheduler_state.INSTANCE_NAME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String instanceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private Long lastCheckinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private Long checkinInterval;
}