package com.example.springboot_quartz.model.dto;

import lombok.Data;

@Data
public class QrtzJobDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.SCHED_NAME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.JOB_NAME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.JOB_GROUP
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String jobGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.DESCRIPTION
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.JOB_CLASS_NAME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String jobClassName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.IS_DURABLE
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String isDurable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.IS_NONCONCURRENT
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String isNonconcurrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.IS_UPDATE_DATA
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String isUpdateData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.REQUESTS_RECOVERY
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String requestsRecovery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.JOB_DATA
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private byte[] jobData;
}