package com.example.springboot_quartz.model.dto;

import lombok.Data;

@Data
public class QrtzCronTriggers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_cron_triggers.SCHED_NAME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_cron_triggers.TRIGGER_NAME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String triggerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_cron_triggers.TRIGGER_GROUP
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String triggerGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_cron_triggers.CRON_EXPRESSION
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String cronExpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_cron_triggers.TIME_ZONE_ID
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String timeZoneId;
}