package com.example.springboot_quartz.model.dto;

import lombok.Data;

@Data
public class QrtzCalendars {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_calendars.SCHED_NAME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_calendars.CALENDAR_NAME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String calendarName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_calendars.CALENDAR
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private byte[] calendar;
}