package com.example.springboot_quartz.model.dto;

import java.math.BigDecimal;
import lombok.Data;

@Data
public class QrtzSimpropTriggers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.SCHED_NAME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.TRIGGER_NAME
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String triggerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.TRIGGER_GROUP
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String triggerGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.STR_PROP_1
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String strProp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.STR_PROP_2
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String strProp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.STR_PROP_3
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String strProp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.INT_PROP_1
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private Integer intProp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.INT_PROP_2
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private Integer intProp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.LONG_PROP_1
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private Long longProp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.LONG_PROP_2
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private Long longProp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.DEC_PROP_1
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private BigDecimal decProp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.DEC_PROP_2
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private BigDecimal decProp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.BOOL_PROP_1
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String boolProp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.BOOL_PROP_2
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    private String boolProp2;
}