package com.example.springboot_quartz.mapper.base;

import com.example.springboot_quartz.model.dto.QrtzPausedTriggerGrps;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface QrtzPausedTriggerGrpsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_paused_trigger_grps
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    int deleteByPrimaryKey(@Param("schedName") String schedName, @Param("triggerGroup") String triggerGroup);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_paused_trigger_grps
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    int insert(QrtzPausedTriggerGrps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_paused_trigger_grps
     *
     * @mbggenerated Thu Jul 18 15:57:05 CST 2019
     */
    List<QrtzPausedTriggerGrps> selectAll();
}